security:

    firewalls:
    
        secured_area:
        
            pattern:  ^/
            anonymous:  ~
            
            provider: memory_provider
            
            form_login:                
                # the user is redirected here when they need to log in
                login_path:  login
                # submit the login form here
                check_path:  login_check
                
            logout:
                path:   /logout
                target: /
                
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }         

    providers:
    
        memory_provider:        
            memory:
                users:
                    admin: { password: RtpzvYHH3SUAw, roles: 'ROLE_ADMIN' }
                
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12