<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository {
	
	private function baseQuery() {
		return $this->createQueryBuilder('c');
	}
	
	private function CommentAccepted($query, $commentAccepted) {
		return $query
		->andWhere('c.commentAccepted = :commentAccepted')
		->setParameter('commentAccepted', $commentAccepted);	
	}
	
	public function findAllByCommentAccepted($commentAccepted) {
	
		$query=$this->CommentAccepted($this->baseQuery(), $commentAccepted);
	
		return $query->getQuery()->getResult();
	}
	
	
}
